project:
  type: website
  
website:
  title: "Math 557 Fall 2025"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: 001_Aug27_syntax.qmd
        text: 8/27 - Syntax of first order logic
      - href: 002_Aug29_semantics.qmd
        text: 8/29 - Semantics of first order logic
      - href: 003_Sep03_validities.qmd
        text: 9/3 - Validities
      - href: 004_Sep05_substitution.qmd
        text: 9/5 - Substitution
      - href: 005_Sep10_implication.qmd
        text: 9/10 - Logical implication
      - href: 006_Sep12_completeness.qmd
        text: 9/12 - Complete theories
      - href: 007_Sep15_completeness_theorem.qmd
        text: 9/15 - Completeness theorem
      - href: 008_Sep17_completing_theories.qmd
        text: 9/17 - Completing theories
      - href: 009_Sep19_Henkin_theories.qmd
        text: 9/19 - Henkin theories
      - href: 010_Sep22_model_existence.qmd
        text: 9/22 - Model existence theorem
      - href: 011_Sep24_compactness.qmd
        text: 9/24 - Compactness theorem
      - href: 012_Sep26_midterm_review.qmd
        text: 9/26 - Midterm 1 review
      - href: 013_Oct01_elementary_equivalence.qmd
        text: 10/1 - Elementary equivalence
      - href: 014_Oct03_elementary_substructures.qmd
        text: 10/3 - Elementary substructures
      - href: 015_Oct06_loewenheim_skolem.qmd
        text: 10/6 - Löwenheim-Skolem Theorems
      - href: 016_Oct08_ultraproducts.qmd
        text: 10/8 - Ultraproducts
      - href: 017_Oct10_week7_problems.qmd
        text: 10/10 - Problems
      - href: 018_Oct13_homogeneous_structures.qmd
        text: 10/13 - Homogeneous structures
      - href: 019_Oct15_fraisse_limits.qmd
        text: 10/15 - Fraïssé limits
      - href: 020_Oct17_random_graphs.qmd
        text: 10/17 - Random graphs
      - href: midterm_2_preparation.qmd
        text: 10/20 - Midterm 2 
      - href: 021_Oct22_computable_functions.qmd
        text: 10/22 - Computable functions
      - href: 022_Oct24_primitive_recursive.qmd
        text: 10/24 - Primtive recursion
      - href: 023_Oct29_peano_arithmetic.qmd
        text: 10/29 - Peano Arithmetic
      - href: 024_Oct31_arithmetical_formulas.qmd
        text: 10/31 - Arithmetical formulas
      - href: 025_Nov3_end_extensions.qmd
        text: 11/3 - End extensions
      - href: 026_Nov5_definability.qmd
        text: 11/5 - Definability of computable functions
      - href: 027_Nov7_PA-proofs.qmd
        text: 11/7 - Practice on PA
      - href: 028_Nov10_representability.qmd
        text: 11/12 - Representability
      - href: 029_Nov14_Goedel_numbers.qmd
        text: 11/14 - Gödelization
      - href: 030_Nov17_diagonal_lemma.qmd
        text: 11/17 - Diagonal Lemma
      - href: 031_Nov19_first_incompleteness.qmd
        text: 11/19 - First Incompleteness Theorem




format:
  html:
    page-navigation: true
    callout-appearance: simple
    callout-icon: false
    filters:
      - callouty-theorem
      - search-replace
      - custom-numbered-blocks
      - parse-latex

    theme:
      - cosmos
      - brand
    css: styles.css
    toc: true
  pdf: 
    documentclass: article
    geometry: "margin=0.8in"
    filters:
      - custom-numbered-blocks

custom-numbered-blocks:
  groups:
    thmlike:
      colors: [F8FBD3, EBEBEB]
      boxstyle: foldbox.simple
      collapse: false
    exrlike:
      colors: [FFE6B4, EBEBEB]
      boxstyle: foldbox.simple
      collapse: false
    takehome:
      colors: [FF7E79, EBEBEB]
      boxstyle: foldbox.simple
      collapse: false

  classes:
    Theorem:
      group: thmlike
    Definition:
      group: thmlike
    Lemma:
      group: thmlike
    Corollary:
      group: thmlike
    Problem:
      group: exrlike
    Exercise:
      group: exrlike
    Take-Home:
      group: takehome

callouty-theorem:
  exr:
    override-title: false
    callout:
      type: tip
      appearance: minimal
  thm:
    override-title: false
    callout:
      type: important
      appearance: simple
  lem:
    override-title: false
    callout:
      type: note
      appearance: simple
  prp:
    override-title: false
    callout:
      type: warning
      appearance: simple
  cor:
    override-title: false
    callout:
      type: warning
      appearance: simple
  def:
    override-title: false
    callout:
      type: note
      appearance: simple
  exm:
    override-title: false
    callout:
      type: tip
      appearance: simple

search-replace:
  +L : $\mathcal{L}$
  +PA : \mathsf{PA}
